<template>
  <UContainer class="pt-5">
    <div class="flex gap-2">
      <div v-for="(breadcrumb, index) in breadcrumbs" class="flex items-center">
          <NuxtLink
            class="text-xs hover:underline cursor-pointer"
            :href="breadcrumb.url"
            :class="{
              'text-gray-200': index === breadcrumbs.length - 1,
              'text-slate-600': index < breadcrumbs.length - 1,

            }"
          >
            {{ breadcrumb.text }}
          </NuxtLink>
          <span v-if="index !== breadcrumbs.length - 1" class="text-slate-700 ml-2 i-heroicons-chevron-right text-xs font-bold" />
      </div>
    </div>
  </UContainer>
</template>

<script lang="ts" setup>

  const breadcrumbs = ref<Breadcrumb[]>([]);
  const route = useRoute();

  const textMap: Record<string, string> = {
    'observations': 'Observation',
    'projects': 'Project',
  }

  function setBreadcrumb(val: string) {
    // remove http(s)://
    val = val.replace(/^http(s)?\:\/\/.+?\//, '');

    // remove leading slash
    val = val.replace(/^\//, '');

    // split by /
    let split = val.split('/');

    // remove empty items from split
    split = split.filter((x) => !!x);

    // remove query params
    if (split.length) {
      split[split.length - 1] = split[split.length - 1].split('?')[0]
    }

    // set initial url (used in loop)
    let url = '/';

    // reset breadcrumbs value that is gonna be filled now
    breadcrumbs.value = []

    // fill breadcrumbs with autogenerated values
    for (let i = 0; i < split.length; i++) {
      const part = split[i];

      // get text from map if its there
      let text = Object.keys(textMap).includes(part) ? textMap[part] : part;

      // add trailing slash to url unless we have only one part
      const trailingSlash = split.length !== 1 ? '/' : '';
      url += part + trailingSlash;

      // capitalize first letter
      text = text.charAt(0).toUpperCase() + text.slice(1);

      // replace underscores with spaces
      text = text.replaceAll('_', ' ');

      // add and push new breadcrumb
      const newBreadcrumb: Breadcrumb = {
        text,
        url,
      }
      breadcrumbs.value.push(newBreadcrumb);
    }
  }

  // every time url changes, regenerate breadcrumb
  watch(
    () => route.fullPath,
    (val) => setBreadcrumb(val),
    { immediate: true }
  )
</script>